### ISSUE TITLE
Create example narrative

### ISSUE THREAD

**Issue by triebnigg** [GTIF-Austria/public-narratives#1]
**Create the exampe of a narrative content.**

Narratives are supposed to go online under the public [GTIF-AT Demonstrator](https://gtif.esa.int/expore) - Narratives Mode entries:
- multimedia-description of GTIF capability
- information products, interface(s), benefits for users
- for agreement with stakeholders instead of lenghty requirements documentation

**Comment by silvester-pari** [comment]
A [first example narrative](https://github.com/GTIF-AT-Consolidation-Activities/public-narratives/blob/1562465a1525f4eb5b4b1d231f7f07d75d149baf/narratives/example.md) has been added as a placeholder, but we can probably provide a better one more suited to the topic.

**Comment by silvester-pari** [comment]
Added in https://github.com/GTIF-Austria/public-narratives/commit/fd3d4010e1dc6341ec3a7b666b0f425d84c02aa3
