### ISSUE TITLE
Narratives publishing

### ISSUE THREAD

**Issue by triebnigg** [GTIF-Austria/public-narratives#2]
As soon as a narrative has been submitted to the repository:

1. it shall be visible under GitHub pages (preview during development phase)
2. once the narrative is ready to be published, it should become visible under the [GTIF-AT Demonstrator](https://gtif.esa.int/explore)

**Comment by silvester-pari** [comment]
Point 1.) implemented in ac0752a74aadf4d4c125ad1287114da447b79bcc.

**Comment by silvester-pari** [comment]
Currently the site needs to be rebuilt manually. It is published under the new domain as discussed. Open point sfor the future:
- automated deployment once a narrative has been pushed
- staging/testing deployment
